#SRAM: 512kB; PSRAM: 4Mb; SPI FLASH: 32Mb
substitutions:
  led_builtin_name: 'Flash'
  led_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'


esp32:
  board: esp32cam #esp32dev
  variant: ESP32
  framework:
    type: esp-idf
    # version: 5.3.1
    # platform_version: 6.9.0
    version: 4.4.8
    platform_version: 5.4.0
psram:
  mode: quad
  speed: 80MHz


esp32_camera:
  name: "${friendly_name}"
  internal: true
  external_clock:
    pin:
      number: 0
      allow_other_uses: true
    frequency: 20MHz
  i2c_pins:
    sda: 26
    scl: 27
  vsync_pin: 25
  href_pin: 23
  pixel_clock_pin: 22
  power_down_pin: 32
  data_pins: [5, 18, 19, 21, 36, 39, 34, 35]

output:
  - platform: gpio
    id: led_builtin_output
    pin:
      number: 4
      allow_other_uses: true

light:
  - platform: binary
    id: led_builtin
    output: led_builtin_output
    name: $led_builtin_name
    internal: $led_builtin_internal

binary_sensor:
  - platform: gpio
    id: button_builtin
    pin:
      number: 0
      allow_other_uses: true
    name: $button_builtin_name
    internal: $button_builtin_internal