substitutions:
  led_builtin_use_psram: 'true'
  led_builtin_rmt_channel: '0'

esp32:
  board: adafruit_metro_esp32s3
  variant: ESP32S3
  framework:
    type: esp-idf
# psram:
#   mode: octal
#   speed: 120MHz


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    is_rgbw: True
    pin: GPIO46
    num_leds: 1
    chipset: SK6812 # ws2812
    name: Built-in Neopixel
    id: led_builtin
    use_psram: $led_builtin_use_psram
    rmt_channel: $led_builtin_rmt_channel