substitutions:
  neopixel_builtin_name: 'Built-in Neopixel'
  neopixel_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'


esp32:
  board: adafruit_qtpy_esp32c3
  variant: ESP32C3
  framework:
    type: esp-idf

wifi:
  output_power: 8.5

# light:
#   - platform: esp32_rmt_led_strip
#     id: neopixel_builtin
#     rgb_order: GRB
#     is_rgbw: True
#     pin: NEOPIXEL
#     num_leds: 1
#     chipset: ws2812 #SK6812

#     name: $neopixel_builtin_name
#     internal: $neopixel_builtin_internal

# binary_sensor:
#   - platform: gpio
#     id: button_builtin
#     pin:
#       number: BUTTON
#       mode: INPUT_PULLUP
#       inverted: true
#     name: $button_builtin_name
#     internal: $button_builtin_internal