substitutions:
  led_builtin_name: 'Built-in Neopixel'
  led_builtin_id: led_builtin


esp32:
  board: adafruit_qtpy_esp32c3
  variant: ESP32C3
  framework:
    type: esp-idf

wifi:
  output_power: 8.5

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    is_rgbw: True
    pin: 2
    num_leds: 1
    chipset: SK6812 # ws2812

    name: $led_builtin_name
    id: $led_builtin_id