substitutions:
  led_builtin_use_psram: 'true'
  led_builtin_name: 'Built-in Neopixel'
  led_builtin_id: led_builtin


esp32:
  board: adafruit_qtpy_esp32s2
  variant: ESP32S2
  framework:
    type: esp-idf

power_supply:
  - id: led_builtin_power
    pin: GPIO38
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    is_rgbw: True
    pin: GPIO39
    power_supply: led_builtin_power
    num_leds: 1
    chipset: SK6812 # ws2812

    name: $led_builtin_name
    id: $led_builtin_id
    use_psram: $led_builtin_use_psram
