substitutions:
  neopixel_builtin_name: 'Built-in Neopixel'
  neopixel_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'


esp32:
  board: adafruit_qtpy_esp32c3
  variant: ESP32C3
  framework:
    type: esp-idf

wifi:
  output_power: 8.5

light:
  - platform: esp32_rmt_led_strip
    id: neopixel_builtin
    rgb_order: GRB
    is_rgbw: True
    pin: NEOPIXEL
    num_leds: 1
    chipset: SK6812 # ws2812

    name: $neopixel_builtin_name
    internal: $neopixel_builtin_internal

binary_sensor:
  - platform: gpio
    id: button_builtin
    pin: BUTTON
    name: $button_builtin_name
    internal: $button_builtin_internal