substitutions:
  neopixel_builtin_name: 'Built-in Neopixel'
  neopixel_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'


esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  variant: ESP32S3
  framework:
    type: esp-idf


power_supply:
  - id: neopixel_builtin_power
    pin: NEOPIXEL_POWER
light:
  - platform: esp32_rmt_led_strip
    id: neopixel_builtin
    rgb_order: GRB
    is_rgbw: True
    pin: NEOPIXEL
    power_supply: neopixel_builtin_power
    num_leds: 1
    chipset: SK6812 # ws2812

    name: $neopixel_builtin_name
    internal: $neopixel_builtin_internal

binary_sensor:
  - platform: gpio
    pin:
      number: BUTTON
      ignore_strapping_warning: true
    id: button_builtin
    name: $button_builtin_name
    internal: $button_builtin_internal

