substitutions:
  led_builtin_use_psram: 'true'
  led_builtin_name: 'Built-in Neopixel'
  led_builtin_id: led_builtin

# 4 MB flash and 2 MB PSRAM
esp32:
  board: adafruit_qtpy_esp32s2
  variant: ESP32S2
  framework:
    type: esp-idf

power_supply:
  - id: led_builtin_power
    pin: GPIO38
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    is_rgbw: True
    pin: GPIO39
    power_supply: led_builtin_power
    num_leds: 1
    chipset: SK6812 # ws2812

    name: $led_builtin_name
    id: $led_builtin_id
    use_psram: $led_builtin_use_psram

# https://learn.adafruit.com/adafruit-qt-py-esp32-s2/pinouts

#   _______________________
# ||-----------------------||
# || 18 < A0  |-|  5V >    ||
# || 17 < A1  |-| GND >    ||
# ||  9 < A2  |-|  3V >    ||
# ||  8 < A3  |-|  MO > 35 ||
# ||  7 < SDA |-|  MI > 37 ||
# ||  6 < SCL |-| SCK > 36 ||
# ||  5 < TX  |-|  RX > 16 ||
# ||-----------------------||
# || NEOPIXEL_power > 38   ||
# || NEOPIXEL > 39         ||
# || SWITCH > 9            ||
# ||_______________________||
#   -----------------------