logger:

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
    entity_category: "diagnostic"
    device_class: connectivity

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    entity_category: "diagnostic"
    device_class: duration

  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    device_class: signal_strength


button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: "diagnostic"

  - platform: factory_reset
    name: "Factory reset"
    entity_category: "diagnostic"

  - platform: shutdown
    name: "Shutdown"
    entity_category: "diagnostic"

  - platform: restart
    name: "Restart"
    entity_category: "diagnostic"
    device_class: restart