logger:

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    entity_category: "diagnostic"

  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""


button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: "diagnostic"

  - platform: factory_reset
    name: "Factory reset"
    entity_category: "diagnostic"

  - platform: shutdown
    name: "Shutdown"
    entity_category: "diagnostic"

  - platform: restart
    name: "Restart"
    entity_category: "diagnostic"