substitutions:
  min_version: 2024.12.0

esphome:
  name: $name
  friendly_name: $friendly_name
  min_version: $min_version

api:
  encryption:
    key: $api_key

ota:
  - platform: esphome
    password: $ota_password
