substitutions:
  mic_sample_rate: 44100
  amp_sample_rate: 44100
  mic_bits_per_sample: 16bit
  amp_bits_per_sample: 16bit
  mic_channel: left
  amp_channel: left
  media_player_id: adf_media_player
  media_player_on_announcement: noop
esp32:
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: main
    components: [ adf_pipeline, i2s_audio ]

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: $I2S1_LR
    i2s_bclk_pin: $I2S1_BLK
  - id: i2s_out
    i2s_lrclk_pin: $amp_lr_pin
    i2s_bclk_pin: $amp_blk_pin


adf_pipeline:

    #mic
  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: $mic_dat_pin
    pdm: false
    channel: $mic_channel
    sample_rate: $mic_sample_rate
    bits_per_sample: $mic_bits_per_sample

    #speaker
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_out
    i2s_dout_pin: $amp_dat_pin
    channel: $amp_channel
    sample_rate: $amp_sample_rate
    bits_per_sample: $amp_bits_per_sample
    # fixed_settings: true



microphone:
  - platform: adf_pipeline
    id: adf_microphone
    pipeline:
      - adf_i2s_in
      - self


media_player:
  - platform: adf_pipeline
    id: $media_player_id
    keep_pipeline_alive: false
    internal: false
    pipeline:
      - self
      # - resampler
      - adf_i2s_out
    on_announcement:
      - script.execute: $media_player_on_announcement
    # on_announcement:
    #   - logger.log: "Announcement started"
    #   - light.turn_on:
    #       id: neo1_ie
    #       blue: 100%
    #       red: 0%
    #       green: 100%
    #       brightness: 50%
    #       effect: "Fast Pulse"
    # on_play:
    #   - logger.log: "Playback started"
    #   - light.turn_on:
    #       id: neo1_ie
    #       blue: 0%
    #       red: 0%
    #       green: 100%
    #       brightness: 50%
    # on_pause:
    #   - logger.log: "Playback paused"
    #   - light.turn_on:
    #       id: neo1_ie
    #       blue: 0%
    #       red: 0%
    #       green: 100%
    #       brightness: 50%
    #       effect: "Slow Pulse"
    # on_idle:
    #   - logger.log: "Playback ended"
    #   - light.turn_off:
    #       id: neo1_ie

script:
  id: noop
  then:
    - delay: 0