substitutions:
  led_builtin_name: 'Status LED'
  led_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'

esp32:
  board: esp32dev
  variant: ESP32
  framework:
    type: esp-idf
light:
  - platform: status_led
    id: led_builtin
    pin:
      number: 2
      ignore_strapping_warning: true

    name: $led_builtin_name
    internal: $led_builtin_internal


binary_sensor:
  - platform: gpio
    id: button_builtin
    pin:
      number: 0
      ignore_strapping_warning: true
    name: $button_builtin_name
    internal: $button_builtin_internal