substitutions:
  neopixel_builtin_use_psram: 'true'
  neopixel_builtin_name: 'Built-in Neopixel'
  neopixel_builtin_internal: 'true'
  button_builtin_name: 'Built-in Button'
  button_builtin_internal: 'true'


external_components:
  - source: github://Option-Zero/esphome-components@max17048
    components: [max17048]


esp32:
  board: adafruit_qtpy_esp32s3_n4r2
  variant: ESP32S3
  framework:
    type: esp-idf
# psram:
#   mode: octal
#   speed: 120MHz


# esphome:
#   platformio_options:
# # added the line below to prevent bootloops when flashing modern bin via serial
#     board_build.flash_mode: dio
power_supply:
  - id: neopixel_builtin_power
    pin: NEOPIXEL_POWER #GPIO38
light:
  - platform: esp32_rmt_led_strip
    id: neopixel_builtin
    rgb_order: GRB
    is_rgbw: True
    # use_psram: false
    pin: PIN_NEOPIXEL #GPIO39 RGB_BUILTIN LED_BUILTIN
    power_supply: neopixel_builtin_power
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812 #SK6812

    name: $neopixel_builtin_name
    use_psram: $neopixel_builtin_use_psram
    internal: $neopixel_builtin_internal

binary_sensor:
  - platform: gpio
    id: button_builtin
    pin:
      number: 0
      ignore_strapping_warning: true
    name: $button_builtin_name
    internal: $button_builtin_internal
