substitutions:
  led_builtin_name: 'Built-in LED'
  led_builtin_internal: 'true'

rp2040:
  board: rpipicow

light:
  - platform: status_led
    pin: GPIO25
    name: $led_builtin_name
    internal: $led_builtin_internal

